Repository TedGoas/Cerberus, pull requests merged in 2022-03, with the labels that each got.

#288 Updated Favicon
  docs/sass/design.scss
  docs/static/images/favicon.svg
  docs/templates/index.html
Labels: bug, Documentation

#289 Add docs on swapping images in dark mode
  docs/content/dark-mode.md
  docs/content/outlook.md
Labels: Documentation

#286 adds to cerberus-hybrid.html
  cerberus-hybrid.html
Labels: bug
